name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build .

#    - name: Package
#      run: |-
#        go get fyne.io/fyne/v2/cmd/fyne
#        cd ./dist
#        fyne package -os darwin -appVersion "0.4.0" -icon icon.png
